### PR TITLE
Documentation on research work for sprint 1

### PR DESCRIPTION
**Pull request by KeerthiKutumbaka**
Added the documentation on AI and ML in Threat Intelligence Platforms for SMEs and Developing Economies.
Added the documentation on Assessing SME's and developing economies cyber threat challenges.
Added the documentation on Existing cybersecurity frameworks and standards applicable to SMEs and developing economies.

### CODE REVIEW

**Comment by KeerthiKutumbaka** [comment]
[Conduct comprehensive research on AI/ML Applications](https://trello.com/c/yxpMGphH/15-conduct-comprehensive-research-on-ai-ml-applications)

**Comment by KeerthiKutumbaka** [comment]
[Conduct comprehensive research on AI/ML Applications](https://trello.com/c/yxpMGphH/15-conduct-comprehensive-research-on-ai-ml-applications)

**Comment by KeerthiKutumbaka** [comment]
[Analyse Cybersecurity Frameworks](https://trello.com/c/v05Cwc5v/14-analyse-cybersecurity-frameworks)

**Comment by KeerthiKutumbaka** [comment]
[Assessing SMEs' and developing economies' cyber threat visibility challenges](https://trello.com/c/xzQror53/13-assessing-smes-and-developing-economies-cyber-threat-visibility-challenges)

**Review by KaylaP001 — APPROVED** [review]

**Pull request merged**
