### PR TITLE
SSH Brute Force Fix

### PR DESCRIPTION
**Pull request by KaylaP001**
SSH Brute Force Fix Manual & Scripts.

### CODE REVIEW

**Comment by KaylaP001** [comment]
[SSH brute force fix manual and script](https://trello.com/c/rmJxbc5b/44-ssh-brute-force-fix-manual-and-script)

**Comment by KaylaP001** [comment]
[SSH brute force fix manual and script](https://trello.com/c/rmJxbc5b/44-ssh-brute-force-fix-manual-and-script)

**Review by jbm1412 — CHANGES_REQUESTED** [review]
The wrong file has been committed. Please send the correct files. Thank You!

**Comment by Shreeyut** [comment]
[Quakbot malware cleanup manual and script](https://trello.com/c/s1VKz2Iz/43-quakbot-malware-cleanup-manual-and-script)

**Review by jbm1412 — APPROVED** [review]

**Pull request merged**
